# Generated by Django 4.0.4 on 2022-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hoursEstimate',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
